<?php

declare(strict_types=1);

return [
    'topics' => [
        'general' => [
            'label' => 'General Information',
            'sidebar' => 'General',
            'items' => [
                ['q' => 'When was the school established?',
                    'a' => 'Pope John Paul II Model Secondary School was established in 2006, originally as Mater Ecclesiae Secondary School, and renamed to its present name in 2007.'],
                ['q' => 'Where is the school located?',
                    'a' => 'The school is located in Umunagbor Amagbor Ihitte, Ezinihitte Mbaise Local Government Area of Imo State, Nigeria.'],
                ['q' => 'What time does the school open?',
                    'a' => 'The school is open Monday to Friday, 7:30 AM to 4:00 PM. The school is closed on Saturdays and Sundays.'],
                ['q' => 'Is it a boarding or day school?',
                    'a' => 'Pope John Paul II Model Secondary School is a full boarding school.'],
                ['q' => 'Is the school for boys only or girls only?',
                    'a' => 'PJP is a co-educational school, admitting both boys and girls.'],
                ['q' => 'What religion does the school practice?',
                    'a' => 'The school is a Christian school under the Catholic Diocese of Ahiara, but admits candidates of various religious backgrounds. Students have opportunities to attend Catholic Mass and Pentecostal assembly within the school.'],
                ['q' => 'Who founded the school?',
                    'a' => 'The school was founded through the vision of Bishop Chikwe, who longed to provide quality education for children of middle and low income earners in the diocese. The building project was sponsored by German donors under the auspices of Ecumenical One World – Saint Nikolaus Wolback, with local support from the Mbaise Educational Development Forum.'],
                ['q' => 'Who is the current principal?',
                    'a' => 'The current principal is Rev. Fr. Ephraim U. Ibekwe, who assumed office in August 2025.'],
                ['q' => 'Is PJP a government or private school?',
                    'a' => 'PJP is a private Catholic school under the Catholic Diocese of Ahiara. It operates in accordance with the National Education Policy and is fully approved by the relevant government bodies.'],
                ['q' => 'How can I contact the school?',
                    'a' => 'You can reach the school by phone on +234 (806) 983-0352 or by email at support@pjp.school. The school office is open Monday to Friday, 7:30 AM to 4:00 PM.'],
            ],
        ],

        'academics' => [
            'label' => 'Academics',
            'sidebar' => 'Academics',
            'items' => [
                ['q' => 'What curriculum does the school operate?',
                    'a' => 'PJP is faithful to the National Education Policy, running both the Junior Secondary (JSS1–JSS3) and Senior Secondary (SSS1–SSS3) curricula, exposing students to a wide range of subjects across Science, Arts and Commercial arms.'],
                ['q' => 'How many arms of classes does the school have?',
                    'a' => 'The school has 8 arms across all classes, with an average of 30 students per class.'],
                ['q' => 'What examination bodies is the school registered with?',
                    'a' => 'The school is registered with WAEC (approved June 2011) and NECO (approved October 2011). The computer laboratory is also an accredited JAMB CBT examination centre.'],
                ['q' => 'What subjects are offered in the Science arm?',
                    'a' => 'Science students study Mathematics, Physics, Chemistry, Biology and Further Mathematics, alongside core subjects. The science laboratories are well equipped to support practical learning.'],
                ['q' => 'What subjects are offered in the Arts arm?',
                    'a' => 'Arts students study Literature in English, History, Government, Christian Religious Studies and Fine Art, among other subjects. The Arts arm trains students who are expressive, analytical and culturally aware.'],
                ['q' => 'What subjects are offered in the Commercial arm?',
                    'a' => 'Commercial students study Commerce, Accounting, Economics and Office Practice. This arm builds the entrepreneurial and financial foundation that students need to lead in business and the economy.'],
                ['q' => 'Are all subjects taught by qualified teachers?',
                    'a' => 'Yes. All subjects at PJP are handled by qualified and experienced teachers. The school maintains a high academic standard and any student wishing to stand out must be prepared to go the extra mile.'],
                ['q' => 'How are students assessed?',
                    'a' => 'Students are assessed through continuous assessment tests, mid-term examinations and end-of-term examinations. Results are published at the end of each term and can be accessed through the school\'s online result portal.'],
                ['q' => 'Does the school prepare students for JAMB?',
                    'a' => 'Yes. The school prepares SS3 students thoroughly for the Unified Tertiary Matriculation Examination (UTME). The school\'s computer laboratory is an accredited JAMB CBT centre, giving students the advantage of practising in a familiar environment.'],
                ['q' => 'How do I check my child\'s result online?',
                    'a' => 'Results can be checked on the school\'s result portal at app.pjp.school. You will need the student\'s registration number, class, term and session. A scratch card pin may be required depending on the school\'s current policy.'],
            ],
        ],

        'facilities' => [
            'label' => 'Facilities',
            'sidebar' => 'Facilities',
            'items' => [
                ['q' => 'What facilities does the school have?',
                    'a' => 'The school has interactive boards in all classrooms, an ICT and Microsoft suite, a well-equipped library, science laboratories, and a school health centre — among other structures necessary for sound moral and academic training.'],
                ['q' => 'How is the hostel accommodation?',
                    'a' => 'The school has separate hostels for boys and girls. The hostels are well ventilated with good toilet facilities and a treated water supply.'],
                ['q' => 'How secure is the school environment?',
                    'a' => 'The school is fully fenced with security guards and modern security gadgets installed around the premises. Optimal security measures are in place at all times to ensure the safety of every student.'],
                ['q' => 'Is there steady power and water supply?',
                    'a' => 'Yes. The school maintains a steady supply of both electricity and treated water to ensure a comfortable and conducive environment for students at all times.'],
                ['q' => 'Does the school have a library?',
                    'a' => 'Yes. The school has a well-equipped library stocked with textbooks, reference materials and supplementary reading resources to support students across all arms and classes.'],
                ['q' => 'Does the school have a chapel?',
                    'a' => 'Yes. As a Catholic institution, the school has a chapel where students attend Mass and engage in spiritual formation. There are also provisions for students of other Christian denominations.'],
                ['q' => 'What ICT resources are available to students?',
                    'a' => 'The school has a robust ICT and Microsoft suite as well as an accredited JAMB CBT computer laboratory. Students are exposed to digital skills as part of their overall formation.'],
            ],
        ],

        'boarding' => [
            'label' => 'Boarding Life',
            'sidebar' => 'Boarding',
            'items' => [
                ['q' => 'How do students do their laundry?',
                    'a' => 'Students do their laundry themselves. They are taught how to do so properly during orientation periods at the beginning of each school year. This is part of the school\'s commitment to building independence and responsibility in every student.'],
                ['q' => 'What level of medical care is available?',
                    'a' => 'The school provides primary and secondary health care services through the school health centre. For cases requiring higher medical attention, the school liaises with standard hospitals close to the school.'],
                ['q' => 'When is visiting day?',
                    'a' => 'Visiting day is every last Sunday of the month. Parents and guardians are warmly welcome to visit their children on this day.'],
                ['q' => 'Does the school observe public holidays?',
                    'a' => 'Yes, the school observes public holidays. However, students are not permitted to go home during public holidays if the school is in session.'],
                ['q' => 'What do students eat — is there a dining hall?',
                    'a' => 'The school provides meals for its boarding students. Students are fed within the school premises as part of the boarding arrangement.'],
                ['q' => 'What should my child bring to school as a boarder?',
                    'a' => 'A full list of boarding requirements — including bedding, toiletries, clothing and stationery — is provided during the admissions process and at the start of each academic year. Parents are advised to follow the official list strictly.'],
                ['q' => 'How is student conduct managed in the hostel?',
                    'a' => 'The school is a strictly coordinated co-educational institution. Housemaster and housemistress staff supervise students in the hostels and maintain discipline in line with the school\'s code of conduct. The school\'s slogan — "You must be different to make the difference" — is lived out in hostel life as much as in the classroom.'],
                ['q' => 'Can students have mobile phones in school?',
                    'a' => 'The use of mobile phones by students is regulated by the school\'s policy. Parents are advised to check the current policy with the school office before sending phones with their children.'],
            ],
        ],

        'sports' => [
            'label' => 'Sports & Co-curricular',
            'sidebar' => 'Sports',
            'items' => [
                ['q' => 'What sporting activities does the school offer?',
                    'a' => 'The school offers a variety of sporting activities including football (soccer), volleyball, table tennis, badminton, indoor games, and field and track events. We believe in developing the whole child — body, mind and spirit.'],
                ['q' => 'Does the school participate in inter-school competitions?',
                    'a' => 'Yes. PJP students participate in inter-school sporting and academic competitions at the local government, state and sometimes national level. These competitions build teamwork, confidence and healthy competition.'],
                ['q' => 'Are there clubs and societies in the school?',
                    'a' => 'Yes. The school encourages students to participate in various clubs and societies that support their intellectual, spiritual and social development. These complement the academic programme and form a key part of the PJP experience.'],
                ['q' => 'Does the school have a debate or quiz team?',
                    'a' => 'Yes. The school actively develops students\' public speaking, critical thinking and argumentation skills through debate and quiz activities. These are seen as key tools in raising confident and articulate future leaders.'],
                ['q' => 'How does the school handle students who are gifted in sports?',
                    'a' => 'Gifted student-athletes are identified and given opportunity to develop and represent the school. However, the school maintains that academic excellence and moral formation must go hand in hand with any co-curricular talent.'],
            ],
        ],

        'admissions' => [
            'label' => 'Admissions',
            'sidebar' => 'Admissions',
            'items' => [
                ['q' => 'How do I apply for admission into PJP?',
                    'a' => 'Admission into PJP is through an entrance examination. Applications can be submitted online through the school\'s entrance exam portal at entrance-exam.pjp.school. You can also visit the school office in person for more information.'],
                ['q' => 'What class levels can I apply for?',
                    'a' => 'Admissions are primarily into JSS1 (Junior Secondary School Year 1) and SSS1 (Senior Secondary School Year 1), subject to availability. Applications into other classes may be considered based on space and academic standing.'],
                ['q' => 'Is there an entrance examination?',
                    'a' => 'Yes. All prospective students must sit and pass the school\'s entrance examination as part of the admissions process. The examination tests the candidate\'s readiness for the level they are applying to.'],
                ['q' => 'What documents are required for admission?',
                    'a' => 'Typically required documents include: birth certificate, primary school leaving certificate (for JSS1 applicants), most recent report card, passport photographs, and a completed application form. Please confirm the full list with the admissions office as requirements may be updated.'],
                ['q' => 'Is the school affordable?',
                    'a' => 'PJP was founded on the vision of making quality education accessible and affordable to children of middle and low income families. The school\'s fee structure reflects that founding commitment. Contact the school office for current fee information.'],
                ['q' => 'Does the school accept students mid-term?',
                    'a' => 'Mid-term admissions are considered on a case-by-case basis depending on availability of space and the student\'s academic records. Prospective parents should contact the school office directly to discuss their situation.'],
            ],
        ],
    ],
];
